version: "2.1"

volumes:
  caddy_data: {}
  mariadb_data: {}

services:
  heimdall:
    image: lspipepr/heimdall:development-fdd5a78e-pkg-16e7a062-pr-109
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - ${APP_DIR}/config:/config
    expose:
      - 80
    restart: unless-stopped

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: heimdall-mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - TZ=Europe/London
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#      - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - mariadb_data:/config
    ports:
      - "33306:3306"
    expose:
      - 3306
    restart: unless-stopped

  caddy:
    image: slothcroissant/caddy-cloudflaredns:2.6.1
    container_name: heimdall-caddy
    ports:
      - "2080:2080"
    volumes:
      - ${APP_DIR}/caddy:/etc/caddy
      - caddy_data:/data
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - HEIMDALL_DOMAIN=${HEIMDALL_DOMAIN}
      - ACME_AGREE=true
    restart: unless-stopped
